from enum import StrEnum


class TenderPackType(StrEnum):
    ITT = "ITT"
    SPECIFICATION = "SPECIFICATION"
    PRICING_SCHEDULE = "PRICING_SCHEDULE"
    EVALUATION_CRITERIA = "EVALUATION_CRITERIA"
    TERMS_AND_CONDITIONS = "TERMS_AND_CONDITIONS"
    CLARIFICATIONS = "CLARIFICATIONS"
